### ISSUE TITLE
Add support for head dimension 128

### ISSUE THREAD

**Issue by perklet** [HazyResearch/ThunderKittens#26]
Most recent models use hdim=128, it would be great to see that ThunderKittens also support that.

https://github.com/HazyResearch/ThunderKittens/blob/a562ed2569c45b0ffea844688594158cb7c6e858/examples/attn/h100/h100_train_atn.py#L25-L26

**Comment by benjaminfspector** [comment]
That is on the eventual to-do list!

**Comment by yifeikong** [comment]
Great! Thanks for the brilliant project!

Are there any pointers on what the block issues are? I would like to try to
fix this on my side.

来自手机回复


Benjamin Spector ***@***.***>于2024年5月16日 周四10:33写道：

**Comment by benjaminfspector** [comment]
looping in @Aaryan0404 for this

**Comment by dz1iang** [comment]
Could you please explain why there is a limitation on the size of the head dimension? I'm not very clear about it.

> That is on the eventual to-do list!

Could you please explain why there is a limitation on the size of the head dimension? I'm not very clear about it.
