### ISSUE TITLE
why there is no zero(attn) before compute q@k.t in h100 example?

### ISSUE THREAD

**Issue by xiayuqing0622** [HazyResearch/ThunderKittens#30]
https://github.com/HazyResearch/ThunderKittens/blob/eab8f21c1addbc52bd013339023f4afa01a5bc57/examples/attn/h100/h100_fwd.cu#L106
Is it bug?

**Comment by Aaryan0404** [comment]
Hi @xiayuqing0622, 

Thanks for your question. So, the clarification here is that `mm_ABt` is different from `mma_ABt` - specifically, the former essentially resets the values in `att_block`, while the latter accumulates _onto_ the values in `att_block` (mma = accumulate, mm = reset).

**Comment by xiayuqing0622** [comment]
> Hi @xiayuqing0622,
> 
> Thanks for your question. So, the clarification here is that `mm_ABt` is different from `mma_ABt` - specifically, the former resets the values in `att_block`, while the latter accumulates _onto_ the values in `att_block`
> 
> (mma = accumulate and mm = reset, which is identical to if `att_block` was zeroed before).

o i see, thank you. :)
